# Generated by Django 4.2.4 on 2023-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contactdatatype_group_contactdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdatatype",
            name="message",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
