# Generated by Django 4.2.4 on 2023-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contactdata_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdatatype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
